stages:
  - validate
  - plan
  - apply
  - destroy

variables:
  IMAGE_TAG: 1.0.${CI_PIPELINE_IID}
  TF_VAR_ENV_NAME: testing
  TF_ROOT: ${CI_PROJECT_DIR}
  BACKEND_CONFIG: backend.tfvars

include:
  - project: 'aws_project1/ci-templates'
    ref: main
    file:
      - terraform-template.yaml

.common:
  tags:
    - docker

validate_infra:
  stage: validate
  tags:
    - docker

plan_infra:
  stage: plan
  tags:
    - docker

apply_infra:
  stage: apply
  tags:
    - docker

destroy_infra:
  stage: destroy
  tags:
    - docker