### GENERAL ###
remote_bucket_name = "s3-remote-backend-eks"
aws_region         = "us-east-1"
### IAM ###
eks_role_name = "EKS-Role"
eks_node_group_role_name = "EKS-Node-Group-Role"
### VPC ###
vpc_cidr_block            = "172.10.0.0/16"
### EKS ###
capacity_type = "ON_DEMAND"
instance_types = ["t2.micro"]
min_size = "1"
desired_size = "1"
max_size = "5"
max_unavailable = "1"
